<?php

namespace Database\Seeders;

use App\Models\Tenant;
use Illuminate\Database\Seeder;

class TenantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Tenant::truncate();

        $tenants = [
            [
                'name' => 'HANABI',
                'idorpassport' => 'PP000001',
                'whatsapp_no' => '0529528339',
                'phone_no' => '0529528339',
                'gender' => 'Female',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 500,
                'previous_balance' => 0,
                'joined_date' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'AARON',
                'idorpassport' => 'PP000002',
                'whatsapp_no' => '0558226594',
                'phone_no' => '0558226594',
                'gender' => 'Male',
                'country_id' => 178,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'ARNOLD',
                'idorpassport' => 'PP000003',
                'whatsapp_no' => '0526387810',
                'phone_no' => '0526387810',
                'gender' => 'Female',
                'country_id' => 178,
                'status' => 0,
                'fixed_deposit' => 500,
                'previous_balance' => 0,
                'joined_date' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'BERNERDO',
                'idorpassport' => 'PP000004',
                'whatsapp_no' => '0544068487',
                'phone_no' => '0544068487',
                'gender' => 'Female',
                'country_id' => 168,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'JUNE',
                'idorpassport' => 'PP000005',
                'whatsapp_no' => '0505155943',
                'phone_no' => '0505155943',
                'gender' => 'Female',
                'country_id' => 168,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'CARINA',
                'idorpassport' => 'PP000006',
                'whatsapp_no' => '0565768801',
                'phone_no' => '0565768801',
                'gender' => 'Female',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 400,
                'previous_balance' => 0,
                'joined_date' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'KAGURA',
                'idorpassport' => 'PP000007',
                'whatsapp_no' => '0556652427',
                'phone_no' => '0556652427',
                'gender' => 'Female',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 100,
                'previous_balance' => 0,
                'joined_date' => now()->subMonth()->subDays(2),
                'created_at' => now()->subMonth()->subDays(2),
                'updated_at' => now()->subMonth()->subDays(2),
            ],
            [
                'name' => 'SHAKIRA',
                'idorpassport' => 'PP000008',
                'whatsapp_no' => '0569363724',
                'phone_no' => '0569363724',
                'gender' => 'Female',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 300,
                'previous_balance' => 0,
                'joined_date' => now()->subMonth()->subDays(2),
                'created_at' => now()->subMonth()->subDays(2),
                'updated_at' => now()->subMonth()->subDays(2),
            ],
            [
                'name' => 'JORDAN',
                'idorpassport' => 'PP000009',
                'whatsapp_no' => '0508764258',
                'phone_no' => '0508764258',
                'gender' => 'Male',
                'country_id' => 168,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonth()->subDays(2),
                'created_at' => now()->subMonth()->subDays(2),
                'updated_at' => now()->subMonth()->subDays(2),
            ],
            [
                'name' => 'JOKER',
                'idorpassport' => 'PP000010',
                'whatsapp_no' => '0567430319',
                'phone_no' => '0567430319',
                'gender' => 'Female',
                'country_id' => 175,
                'status' => 0,
                'fixed_deposit' => 500,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(2)->subDays(2),
                'created_at' => now()->subMonths(2)->subDays(2),
                'updated_at' => now()->subMonths(2)->subDays(2),
            ],
            [
                'name' => 'SHAH RUKH KHAN',
                'idorpassport' => 'PP000011',
                'whatsapp_no' => '0555434874',
                'phone_no' => '0555434874',
                'gender' => 'Male',
                'country_id' => 126,
                'status' => 0,
                'fixed_deposit' => 400,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(2)->subDays(2),
                'created_at' => now()->subMonths(2)->subDays(2),
                'updated_at' => now()->subMonths(2)->subDays(2),
            ],
            [
                'name' => 'SMILE',
                'idorpassport' => 'PP000012',
                'whatsapp_no' => '0563667030',
                'phone_no' => '0563667030',
                'gender' => 'Female',
                'country_id' => 168,
                'status' => 0,
                'fixed_deposit' => 340,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(2)->subDays(2),
                'created_at' => now()->subMonths(2)->subDays(2),
                'updated_at' => now()->subMonths(2)->subDays(2),
            ],
            [
                'name' => 'BALOTTALI',
                'idorpassport' => 'PP000013',
                'whatsapp_no' => '562581975',
                'phone_no' => '562581975',
                'gender' => 'Male',
                'country_id' => 110,
                'status' => 0,
                'fixed_deposit' => 400,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(2)->subDays(2),
                'created_at' => now()->subMonths(2)->subDays(2),
                'updated_at' => now()->subMonths(2)->subDays(2),
            ],
            [
                'name' => 'JANNY',
                'idorpassport' => 'PP000014',
                'whatsapp_no' => '0553632415',
                'phone_no' => '0553632415',
                'gender' => 'Male',
                'country_id' => 168,
                'status' => 0,
                'fixed_deposit' => 300,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(2)->subDays(2),
                'created_at' => now()->subMonths(2)->subDays(2),
                'updated_at' => now()->subMonths(2)->subDays(2),
            ],
            [
                'name' => 'JANNA',
                'idorpassport' => 'PP000015',
                'whatsapp_no' => '0563001682',
                'phone_no' => '0563001682',
                'gender' => 'Female',
                'country_id' => 175,
                'status' => 0,
                'fixed_deposit' => 400,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(3)->subDays(2),
                'created_at' => now()->subMonths(3)->subDays(2),
                'updated_at' => now()->subMonths(3)->subDays(2),
            ],
            [
                'name' => 'GALIBABA',
                'idorpassport' => 'PP000016',
                'whatsapp_no' => '0553570314',
                'phone_no' => '0553570314',
                'gender' => 'Male',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 500,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(3)->subDays(2),
                'created_at' => now()->subMonths(3)->subDays(2),
                'updated_at' => now()->subMonths(3)->subDays(2),
            ],
            [
                'name' => 'MASON',
                'idorpassport' => 'PP000017',
                'whatsapp_no' => '0567603518',
                'phone_no' => '0567603518',
                'gender' => 'Female',
                'country_id' => 168,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(4)->subDays(2),
                'created_at' => now()->subMonths(4)->subDays(2),
                'updated_at' => now()->subMonths(4)->subDays(2),
            ],
            [
                'name' => 'LISA',
                'idorpassport' => 'PP000018',
                'whatsapp_no' => '0559614458',
                'phone_no' => '0559614458',
                'gender' => 'Female',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 200,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(4)->subDays(2),
                'created_at' => now()->subMonths(4)->subDays(2),
                'updated_at' => now()->subMonths(4)->subDays(2),
            ],
            [
                'name' => 'TIN TIN AYE',
                'idorpassport' => 'PP000019',
                'whatsapp_no' => '0565745685',
                'phone_no' => '0565745685',
                'gender' => 'Female',
                'country_id' => 153,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(4)->subDays(2),
                'created_at' => now()->subMonths(4)->subDays(2),
                'updated_at' => now()->subMonths(4)->subDays(2),
            ],
            [
                'name' => 'PHYU PHYU',
                'idorpassport' => 'PP000020',
                'whatsapp_no' => '0589374431',
                'phone_no' => '0589374431',
                'gender' => 'Female',
                'country_id' => 153,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(4)->subDays(2),
                'created_at' => now()->subMonths(4)->subDays(2),
                'updated_at' => now()->subMonths(4)->subDays(2),
            ],
            [
                'name' => 'MIYA',
                'idorpassport' => 'PP000021',
                'whatsapp_no' => '0504841395',
                'phone_no' => '0504841395',
                'gender' => 'Female',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 400,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(5)->subDays(2),
                'created_at' => now()->subMonths(5)->subDays(2),
                'updated_at' => now()->subMonths(5)->subDays(2),
            ],
            [
                'name' => 'MOLINA',
                'idorpassport' => 'PP000022',
                'whatsapp_no' => '0524202960',
                'phone_no' => '0524202960',
                'gender' => 'Female',
                'country_id' => 175,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(5)->subDays(2),
                'created_at' => now()->subMonths(5)->subDays(2),
                'updated_at' => now()->subMonths(5)->subDays(2),
            ],
            [
                'name' => 'ARSHA',
                'idorpassport' => 'PP000023',
                'whatsapp_no' => '0566019458',
                'phone_no' => '0566019458',
                'gender' => 'Female',
                'country_id' => 175,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(5)->subDays(2),
                'created_at' => now()->subMonths(5)->subDays(2),
                'updated_at' => now()->subMonths(5)->subDays(2),
            ],
            [
                'name' => 'ELSA',
                'idorpassport' => 'PP000024',
                'whatsapp_no' => '0588841996',
                'phone_no' => '0588841996',
                'gender' => 'Male',
                'country_id' => 200,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(5)->subDays(2),
                'created_at' => now()->subMonths(5)->subDays(2),
                'updated_at' => now()->subMonths(5)->subDays(2),
            ],
            [
                'name' => 'JOLA',
                'idorpassport' => 'PP000025',
                'whatsapp_no' => '0568507506',
                'phone_no' => '0568507506',
                'gender' => 'Female',
                'country_id' => 175,
                'status' => 0,
                'fixed_deposit' => 200,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(5)->subDays(2),
                'created_at' => now()->subMonths(5)->subDays(2),
                'updated_at' => now()->subMonths(5)->subDays(2),
            ],
            [
                'name' => 'ZHYN MALIK',
                'idorpassport' => 'PP000026',
                'whatsapp_no' => '0543619288',
                'phone_no' => '0543619288',
                'gender' => 'Male',
                'country_id' => 201,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(6)->subDays(2),
                'created_at' => now()->subMonths(6)->subDays(2),
                'updated_at' => now()->subMonths(6)->subDays(2),
            ],
            [
                'name' => 'JARBI',
                'idorpassport' => 'PP000027',
                'whatsapp_no' => '0501653054',
                'phone_no' => '0501653054',
                'gender' => 'Female',
                'country_id' => 218,
                'status' => 0,
                'fixed_deposit' => 200,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(6)->subDays(2),
                'created_at' => now()->subMonths(6)->subDays(2),
                'updated_at' => now()->subMonths(6)->subDays(2),
            ],
            [
                'name' => 'POLA',
                'idorpassport' => 'PP000028',
                'whatsapp_no' => '05504057965',
                'phone_no' => '05504057965',
                'gender' => 'Female',
                'country_id' => 175,
                'status' => 0,
                'fixed_deposit' => 500,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(6)->subDays(2),
                'created_at' => now()->subMonths(6)->subDays(2),
                'updated_at' => now()->subMonths(6)->subDays(2),
            ],
            [
                'name' => 'GARLIE',
                'idorpassport' => 'PP000029',
                'whatsapp_no' => '0552853865',
                'phone_no' => '0552853865',
                'gender' => 'Male',
                'country_id' => 218,
                'status' => 0,
                'fixed_deposit' => 400,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(7)->subDays(2),
                'created_at' => now()->subMonths(7)->subDays(2),
                'updated_at' => now()->subMonths(7)->subDays(2),
            ],
            [
                'name' => 'JANE FORR THU',
                'idorpassport' => 'PP000030',
                'whatsapp_no' => '0558154919',
                'phone_no' => '0558154919',
                'gender' => 'Female',
                'country_id' => 175,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(7)->subDays(2),
                'created_at' => now()->subMonths(7)->subDays(2),
                'updated_at' => now()->subMonths(7)->subDays(2),
            ],
            [
                'name' => 'LEE MIN HO',
                'idorpassport' => 'PP000031',
                'whatsapp_no' => '0501108060',
                'phone_no' => '0501108060',
                'gender' => 'Female',
                'country_id' => 218,
                'status' => 0,
                'fixed_deposit' => 119,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(7)->subDays(2),
                'created_at' => now()->subMonths(7)->subDays(2),
                'updated_at' => now()->subMonths(7)->subDays(2),
            ],
            [
                'name' => 'JAKIE CHAN',
                'idorpassport' => 'PP000032',
                'whatsapp_no' => '0525592704',
                'phone_no' => '0525592704',
                'gender' => 'MALE',
                'country_id' => 46,
                'status' => 0,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(7)->subDays(2),
                'created_at' => now()->subMonths(7)->subDays(2),
                'updated_at' => now()->subMonths(7)->subDays(2),
            ],
            [
                'name' => 'Liu Yin Fei',
                'idorpassport' => 'PP000033',
                'whatsapp_no' => '0527622238',
                'phone_no' => '0527622238',
                'gender' => 'Female',
                'country_id' => 46,
                'status' => 0,
                'fixed_deposit' => 100,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(7)->subDays(2),
                'created_at' => now()->subMonths(7)->subDays(2),
                'updated_at' => now()->subMonths(7)->subDays(2),
            ],
            [
                'name' => 'MARCELO',
                'idorpassport' => 'PP000034',
                'whatsapp_no' => '0558153496',
                'phone_no' => '0558153496',
                'gender' => 'Male',
                'country_id' => 32,
                'status' => 1,
                'fixed_deposit' => 300,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(7)->subDays(2),
                'created_at' => now()->subMonths(7)->subDays(2),
                'updated_at' => now()->subMonths(7)->subDays(2),
            ],
            [
                'name' => 'OSCAR',
                'idorpassport' => 'PP000035',
                'whatsapp_no' => '0545989838',
                'phone_no' => '0545989838',
                'gender' => 'Male',
                'country_id' => 32,
                'status' => 1,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(8)->subDays(2),
                'created_at' => now()->subMonths(8)->subDays(2),
                'updated_at' => now()->subMonths(8)->subDays(2),
            ],
            [
                'name' => 'NEYMAR',
                'idorpassport' => 'PP000036',
                'whatsapp_no' => '0562575323',
                'phone_no' => '0562575323',
                'gender' => 'Male',
                'country_id' => 32,
                'status' => 1,
                'fixed_deposit' => 100,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(8)->subDays(2),
                'created_at' => now()->subMonths(8)->subDays(2),
                'updated_at' => now()->subMonths(8)->subDays(2),
            ],
            [
                'name' => 'JONATHANE',
                'idorpassport' => 'PP000037',
                'whatsapp_no' => '0527734213',
                'phone_no' => '0527734213',
                'gender' => 'Female',
                'country_id' => 218,
                'status' => 1,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(8)->subDays(2),
                'created_at' => now()->subMonths(8)->subDays(2),
                'updated_at' => now()->subMonths(8)->subDays(2),
            ],
            [
                'name' => 'LESLAY',
                'idorpassport' => 'PP000038',
                'whatsapp_no' => '0557204486',
                'phone_no' => '0557204486',
                'gender' => 'Female',
                'country_id' => 159,
                'status' => 1,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(8)->subDays(2),
                'created_at' => now()->subMonths(8)->subDays(2),
                'updated_at' => now()->subMonths(8)->subDays(2),
            ],
            [
                'name' => 'BARUDA',
                'idorpassport' => 'PP000039',
                'whatsapp_no' => '0520000000',
                'phone_no' => '0520000000',
                'gender' => 'Male',
                'country_id' => 128,
                'status' => 1,
                'fixed_deposit' => 0,
                'previous_balance' => 0,
                'joined_date' => now()->subMonths(8)->subDays(2),
                'created_at' => now()->subMonths(8)->subDays(2),
                'updated_at' => now()->subMonths(8)->subDays(2),
            ],
        ];

        foreach ($tenants as $key => $value) {
            Tenant::create($value);
        }
    }
}
