<?php

namespace Database\Seeders;

use App\Models\Transaction;
use Illuminate\Database\Seeder;

class TransactionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Transaction::truncate();

        $transactions = [
            [
                'invoice_no' => '1000000010',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 10,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 10,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '1000',
                'currency' => 'AED',
                'sub_total' => '1000',
                'total_price' => '1000',
                'payment_amount' => '700',
                'balance' => '300',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000009',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 9,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 9,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '1100',
                'currency' => 'AED',
                'sub_total' => '1100',
                'total_price' => '1100',
                'payment_amount' => '600',
                'balance' => '500',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000008',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 8,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 8,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '700',
                'currency' => 'AED',
                'sub_total' => '700',
                'total_price' => '700',
                'payment_amount' => '700',
                'balance' => '0',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000007',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 7,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 7,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '700',
                'currency' => 'AED',
                'sub_total' => '700',
                'total_price' => '700',
                'payment_amount' => '700',
                'balance' => '0',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000006',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 6,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 6,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '700',
                'currency' => 'AED',
                'sub_total' => '700',
                'total_price' => '700',
                'payment_amount' => '700',
                'balance' => '0',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000005',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 5,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 5,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '700',
                'currency' => 'AED',
                'sub_total' => '700',
                'total_price' => '700',
                'payment_amount' => '700',
                'balance' => '0',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000004',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 4,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 4,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '750',
                'currency' => 'AED',
                'sub_total' => '750',
                'total_price' => '750',
                'payment_amount' => '750',
                'balance' => '0',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000003',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 3,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 3,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '1000',
                'currency' => 'AED',
                'sub_total' => '1000',
                'total_price' => '1000',
                'payment_amount' => '500',
                'balance' => '500',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000002',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 2,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 2,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '750',
                'currency' => 'AED',
                'sub_total' => '750',
                'total_price' => '750',
                'payment_amount' => '750',
                'balance' => '0',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
            [
                'invoice_no' => '1000000001',
                'invoice_prefix' => 'AA',
                'invoice_status' => 'fully_paid',
                'invoice_type' => 'payment',
                'tenant_id' => 1,
                'building_id' => 1,
                'floor_id' => 1,
                'flat_id' => 1,
                'partition_id' => 1,
                'no_of_tenant' => 1,
                'start_date' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'end_date' => now()->subDays(3)->toDateTimeString(),
                'price' => '750',
                'currency' => 'AED',
                'sub_total' => '750',
                'total_price' => '750',
                'payment_amount' => '750',
                'balance' => '0',
                'created_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
                'updated_at' => now()->subMonth()->subDays(2)->toDateTimeString(),
            ],
        ];

        foreach ($transactions as $key => $value) {
            Transaction::create($value);
        }
    }
}
